---
title: "Goal Setting"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

<br>

***

# General Information

<br>

### Tutorial 1: Building SMART Goals into Your Planner

Now that you have an idea of how your semester will look and when your key deadlines are, you have a timeframe in which you can create **SMART** goals for interacting with your lecture content. **SMART** stands for:

<br>

**S**pecific 

* **What** do you want to achieve from your online and/or on-campus lectures? 
* **Why** are these lectures important to you?
* **Who** is involved in your lecture related goals?
* **Where** will you lecture goals take place?
* **Which** resources/ limits are involved in achieving your goals for lectures?

<br>

**M**easurable 

* What will you measure to assess your progress?  The number of understood lectures? The number of quality notes written during and/or after your lectures?
* _Quantify_ your goal so you will know when you have achieved it!

<br>

**A**chievable 

* Although it will stretch me, is my goal doable?
* Will I be able to _attend_ all of my lectures live (either on campus or through an online learning platform)?
* Do I have some unavoidable commitment whereby I will have to set a goal to catch up on a lecture using lecture recording in my own time?

<br>

**R**ealistic 

* Is my lecture goal worthwhile?
* Is this the right time to pursue my goal?

<br>

**T**imely 

* When will it be completed?
* How long will it take to complete?
* What can I do today in the time that I have in order to make progress on my goal?

<br>

Using your semester planner, and the resources in this section, try to create a **SMART** goal that you could insert into your weekly planner. For example, you may have already identified a difficult section in a recent lecture that you want to better understand. Think about the steps that you will take to get a better understanding of that topic using your lecture materials (e.g. for notes, see the [_next section_](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Note_Taking.html)). Think about how you will incorporate lecture recordings as a step in achieving your **SMART** goal. To help you do this, watch the YouTube video on the following page ([_Task 1_](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Goal_Setting.html#task_1)).

After completing the exercises in this section, you could transfer your **SMART** goal knowledge to a computer/ mobile app for convenience (see additional resources). Also, remember to add time to your timetable (online or offline) to reflect on your **SMART** goal progress. Ask yourself what is going well and what you need to change to accomplish your goal. For more information on reflection, see [_Going Forward_](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Going_Forward.html).

<br>

# An Overview of SMART Goals

<br>

### Task 1: Watch this Video on SMART goals

To get a quick overview of what **SMART** goals are, take a look at this informative video. Whilst watching this video, think about how your university experience will look and how **SMART** goals will fit into your own timetable. Specifically, think about whether you will be engaging with lectures on campus, remotely or through a blended approach. This means that your **SMART** goals should be tailored to _who_ you are as a student. Think about the goals that you have for learning with lectures and how you will implement them in the specific learning environment that you will be in. 

<br>

<center>

<iframe width="560" height="315" src="https://www.youtube.com/embed/1-SvuFIQjK8" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</center>  

<br>

# Examples of (not so) SMART Goals

<br> 

### Resources

Compare and contrast the two examples of **SMART** goals. The bad example is not specific, does not provide a measurable outcome, and is not time-bound in clear way. You should **be as specific as possible** with your goals' 5 components (**S.M.A.R.T.**)

* [Example of a Bad SMART Goal](downloads/SMART_Bad_Example.pdf
)

* [Example of a Good SMART Goal](downloads/SMART_Good_Example.pdf
)

<br>

# Making your Own SMART Goals

<br>

### Task 2: Use the Template to Make Your Own SMART Goal

* [Blank Template for SMART goals](downloads/SMART_template.docx)

<br>

# Implementing and Achieving Your SMART Goals

<br>

### Tutorial 2: Tips on Seeing your Goals Through

<br>

Making **SMART** goals can be easy; but implementing them can sometimes be tricky. Read this short tutorial for some top tips on how best to implement your **SMART** goals. After you have developed **SMART** goals (for instance, using lecture recordings to clarify a difficult online lecture), the next step is taking action to successfully implement these goals. Implementing your **SMART** goals requires planning, executing, and monitoring your progress towards your goals. 

<br>

**Planning**

* Thoroughly establish the subgoals that will lead to you successfully completing your **SMART** goal. Think about _exactly_ what you need to do and when to achieve your goal. Creating an explicit link between _what_ you have to do and _when_ you have to do it increases the likelihood of the goal being implemented.

<br>

**Executing**

* Take concrete and decisive action to implement the subgoals.

<br>

**Monitoring**

* As you work towards your goal, take note of things that are going well and things that are not going so well. Update your **SMART** goals (and subgoals) accordingly.

<br>

Here are some top tips for implementing your **SMART** lecture goals:

<br>

1. Insert your subgoals into your weekly planner.
2. Make your subgoals high priority in your planner and complete them early in the day.
3. Use a [_daily planner_](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Additional_Resources.html#time_keeping) app on your phone to further breakdown the daily steps you can take.
4. Write your **SMART** goal somewhere you will see it daily.
5. Check off the subgoal milestones as you complete them so you can see the progress that you are making (use a [_checklist app_](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Additional_Resources.html#goal_setting)).
6. Share your **SMART** goals with other people (for example, a study group) so you can be supported and encouraged by others. You might even be held accountable!
7. Collect all the materials you need to implement your goal in advance.
8. Complete at least one action per day.
9. Reward yourself when you implement your **SMART** goals.

<br>

# Going Forward

The [_Going Forward_](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Going_Forward.html) section contains a useful [checklist](downloads/checklist.docx) for keeping track of how much you have learned from this topic.