---
title: "Making the Most of Lectures"
output: html_document
---

Welcome to _Making the Most of Lectures_: an interactive course that has been designed to help you use lectures and lecture recordings to enhance your remote and/ or on-campus learning. Drawing on evidence-based techniques, this non-credit course will introduce you to some of the ways in which you can integrate lectures and lecture recordings (if available) into your studying. The information contained within this course will be useful for students taking courses on campus and for those who will be studying courses remotely (or a mixture of both). 

Whilst it is not necessary to work through the materials sequentially, starting with the first section and working your way to the final section may be the most rewarding approach. The materials have been organised in this order to allow you to build on the skills you will have learned in previous sections. If you are enrolled in courses in which you will be attending classes online, then working through this course will also help you to get the necessary skills to be an effective online learner, such as [_time keeping_](https://g33h3m.github.io/MakingtheMostofLectures/Time_Keeping.html), _goal setting_, and _note taking_. For specific information on how to make the most of virtual learning, check out the _online learning_ section.  

Although completing the entire course at the start of the semester is preferable, you can implement the information and skills you learn in the course at any time. If it is near exams, then _goal setting_ and _revising_ might be a good place to start. If you are enrolled in any online courses, then reflect on the information in _online learning_ in order to think about how you will implement your new evidence-based skills (from the other sections) in an online learning environment. 

Finally, the skills you will learn here have been chosen because they work well together; but this course is in no way exclusive nor exhaustive. We encourage you to reflect on who you are as student and what your learning environment is like, using what you learn here as a springboard into exploring effective study strategies and the use of lectures (online and on campus) and lecture recordings in more depth.

**This course was designed by psychology student, Graham Reid.**