---
title: "Note Taking"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

<br>

***

# General Information

<br>

### Tutorial: An Overview of the Cornell Method

Whether you are engaging with on-campus or online lectures, it is likely that you will be taking your fair share of notes as a student. Indeed, when it comes to [_revising_](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Revising.html) for your exams you will be using your notes a lot. Whilst there are many different styles of notes that one can take, the general advice is that you should **not** be writing down information verbatim. It is far more useful and effective for your memory if you actively think about what you are hearing and summarise it in your own words. One fairly prominent method of taking notes in the literature is called the _Cornell Method_. To get an overview of what the Cornell Method of effective note taking is, take a look at this brief informative video. If when watching this tutorial you identify any areas in which you could improve your skills, implement what you have learned in the [_**SMART** goal_](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Goal_Setting.html) section by thinking about how you will get better at note taking. In addition, use what you learned in the [_time keeping_](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Time_Keeping.html) section to proactively create time to implement your **SMART** goal. 

<br>

<center>

<iframe width="560" height="315" src="https://www.youtube.com/embed/ErSjc1PEGKE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</center>

Remember that after completing the exercises in this section, you can transfer what you learn onto a mobile/ computer app (see [_additional resources_](https://g33h3m.github.io/MakingtheMostofLectures/Additional_Resources.html)).

<br>

# Examples of Lecture Notes

<br> 

### Resources

Hopefully, the short video has shown you the utility of taking efficient notes during your [_online_](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Online_Learning.html) and/or on-campus lectures. Looking at the example of Cornell notes in this section, you will see some bullet points in the left margin that are dedicated to the later use of lecture recording. 

In an initial lecture (on campus or virtual), if you identify a difficult concept, jot down the slide and rough time so that you can review the specific part of the recording later.

When note-taking try to organise your notes in your own words and in your own way. Connect new information to old information and jot that connection down to help it stick in your memory.

After completing the exercises in this section, remember that you can always transfer your knowledge and skills onto a computer/ mobile app for convenience (see [_additional resources_](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Additional_Resources.html#note_taking)).

* [Example of Cornell Notes](downloads/Cornell_Notes_Example.pdf
)

<br>

# Trying a Pratice 'Lecture'

<br>

### Task 2.1: Watch This Video

Watch _TED's secret to great public speaking_ as your practice lecture and try taking Cornell style notes using the blank template below.

<br>

<center>

<iframe width="560" height="315" src="https://www.youtube.com/embed/-FOCpMAww28" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</center>

<br>

# Taking Your Own Notes 

<br>

### Note-taking template for the Cornell Method

* [Blank Template for Cornell Notes](downloads/Cornell_Notes_Template.pdf)

<br>

# Going Forward

The [_Going Forward_](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Going_Forward.html) section contains a useful [checklist](downloads/checklist.docx) for keeping track of how much you have learned from this topic.