---
title: "Seeking Help"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

<br>

***

# Information

Here you will find some information on effective strategies in getting extra support on lecture content. Remember that just because you have a lecture recording doesn't mean that you have been left to your own devices. If you need extra support, then help is there for you.

<br>

### What To Do If You Have a Persistant Issue With a Section of a Lecture?

<br>

#### Staff Office Hours

If you are having difficulties with any aspect of your (online and/or on-campus) course, you can go along to speak to your lecturers or in some cases it might be preferable to arrange a virtual appointment with them (e.g. Zoom). All teaching staff at the University of Glasgow will have a weekly time-slot for meeting in person and/ or virtually with their students. Staff are dedicated to the students, so you can be confident that they are likely to be available to speak to you. Staff office hours tend to be underused by students, so you should make the most of the 1-2-1 with the staff who are teaching you. To find a staff member’s office hour, follow the link below, which gives you a list of the different schools at the university. From there, choose the relevant School. Next, click on the *our staff* section. Find the member of staff whose office hour you would like to attend and look at their profile where you will find their office hours (or their email address if there is no published office hour). Remember that staff often put their office hours on the first slide of their lecture presentations (sometimes only for the first lecture in the semester). In some circumstances staff office hours might be subject to frequent change, so you can always send an email to the staff member to find out their availability for that week. It is also a good idea to have a conference call application (e.g. Microsoft Teams or Zoom) installed on your devices in case you have to arrange a virtual meeting (see [online learning](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Online_Learning.html#useful_resources) for more information on such applications). 

https://www.gla.ac.uk/schools/

<br>

#### Peer Assisted Learning (PAL)

Some Schools at the university offer a system in which older students are available to support younger students (and vice versa) with course related content. If you are struggling with some lecture content, why not take the lecture recording to a PAL session and see if a fellow student can support you in some way? To find out if your school offers PAL, contact your course convenor.

<br>

#### Create a Study Group

Research has shown the use of student study groups to be an effective learning strategy. Studying in groups not only gives you the opportunity to support each other, but you can work collaboratively on difficult lecture topics. Having a structured study group will allow you to practise active recall by explaining lecture topics to each other, to fill in any gaps in your notes, and to break the monotony of studying alone. Why not revisit specific lecture recordings together and tackle the difficult topics together? Working together may help you gain insight into lecture content that you wouldn't have got alone. You can post on your course's Moodle announcement section to see if any of your peers would like to start a study group. 

Remember that you can use technology such as Zoom or Microsoft Teams to set up a virtual study group. These applications allow you to share your computer screen with your fellow students. This could be useful for watching lecture recordings together, or for sharing diagrams and infographics with each other. Virtual study groups might be preferable to on-campus study groups (e.g. you are a home student or your course is being delivered remotely), so you should make the most of available technology to study with your peers (see [online learning](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Online_Learning.html#useful_resources) for more information).

<br>

# Going Forward

The [Going Forward](https://grahamreidpsychology.github.io/MakingtheMostofLectures/Going_Forward.html) section contains a useful [checklist](downloads/checklist.docx) for keeping track of how much you have learned from this topic.